### PR TITLE
build: update assets.tar, in case of update

### PR DESCRIPTION
**Pull request by Horki**

### CODE REVIEW

**Comment by Horki** [comment]
@ozkriff please test #631

**Comment by ozkriff** [comment]
Hey, thanks for the PR, but I was hoping to keep these shell scripts as simple and straightforward as possible. Maybe it's better to just remove the condition and create a new archive on every script run? It's not like Zemeroth will ever have a significant amount of assets anyway. :thinking:

**Comment by Horki** [comment]
@ozkriff sounds reasonable, I have removed unnecessary code, please test

**Review by ozkriff — APPROVED** [review]

**Comment by ozkriff** [comment]
Thanks, merged!

**Pull request merged**
